# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "B:\CLion 2021.1.2\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "B:\CLion 2021.1.2\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = B:\OpenMP_lab

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = B:\OpenMP_lab\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "B:\CLion 2021.1.2\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "B:\CLion 2021.1.2\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start B:\OpenMP_lab\cmake-build-debug\CMakeFiles B:\OpenMP_lab\cmake-build-debug\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start B:\OpenMP_lab\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mp

# Build rule for target.
mp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) mp
.PHONY : mp

# fast build rule for target.
mp\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\mp.dir\build
.PHONY : mp\fast

#=============================================================================
# Target rules for targets named without_mp

# Build rule for target.
without_mp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) without_mp
.PHONY : without_mp

# fast build rule for target.
without_mp\fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\without_mp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\without_mp.dir\build
.PHONY : without_mp\fast

main.obj: main.c.obj

.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\mp.dir\main.c.obj
.PHONY : main.c.obj

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\mp.dir\main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\mp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\mp.dir\main.c.s
.PHONY : main.c.s

main_without_mp.obj: main_without_mp.c.obj

.PHONY : main_without_mp.obj

# target to build an object file
main_without_mp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\without_mp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\without_mp.dir\main_without_mp.c.obj
.PHONY : main_without_mp.c.obj

main_without_mp.i: main_without_mp.c.i

.PHONY : main_without_mp.i

# target to preprocess a source file
main_without_mp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\without_mp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\without_mp.dir\main_without_mp.c.i
.PHONY : main_without_mp.c.i

main_without_mp.s: main_without_mp.c.s

.PHONY : main_without_mp.s

# target to generate assembly for a file
main_without_mp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\without_mp.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\without_mp.dir\main_without_mp.c.s
.PHONY : main_without_mp.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... mp
	@echo ... without_mp
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... main_without_mp.obj
	@echo ... main_without_mp.i
	@echo ... main_without_mp.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

